Improve express.js logic, skip Edge in browser check
unicef/etools-epd pull request #291
Opened 2021-09-20 14:58 UTC by v-urbanovich

2021-09-20 18:39 UTC, robertavram requested changes

2021-09-20 18:39 UTC, robertavram commented on upgrade-browser.html
> +    Please, upgrade your browser
This current browser or browser version is unsupported. Instead we recommend using the latest version of <a tag to download chrome>Chrome </a>

2021-09-20 18:39 UTC, robertavram commented on express.js
> +const UAParser = require('ua-parser-js').UAParser; // eslint-disable-line
if we add this package it would need to be added to the dockerfile otherwise the built version will not work.
However I think we can get around having this package by taking the useragent from the request directly:
request.headers['user-agent'] and check against that. Another option could be to use UAParser instead of client capabilities (since the only thing we're using is to check if modules are supported)

2021-09-21 06:52 UTC, v-urbanovich commented on express.js
> +const UAParser = require('ua-parser-js').UAParser; // eslint-disable-line
But this package is used internally by browser-capabilities, so it would be installed anyway

2021-09-21 14:48 UTC, robertavram commented on express.js
> +const UAParser = require('ua-parser-js').UAParser; // eslint-disable-line
oh great.. nevermind my comment then..

2021-09-21 15:25 UTC, merged